env: "local"
http_server:
  address: "localhost/8082"
  timeout: 4s
  idle_timeout: 60s
storage:
  storage_path: "./storage/storage.db"
  host: "localhost"
  port: "5432"
  database: "postgresql"
  username: "postgresql"
  password: "postgresql"
  max_attempts: 5
